apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-pvc
  labels:
    name: mysql-pod-pvc
    #context: docker-k8s-lab
spec:
  containers:
    - name: mysql
      image: mysql:latest
      env:
        - name: "MYSQL_USER"
          value: "eazy"
        - name: "MYSQL_PASSWORD"
          value: "eazy"
        - name: "MYSQL_DATABASE"
          value: "eazytraining"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "password"
      ports:
        - containerPort: 3306
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: data-volume-pvc
  volumes:
    - name: data-volume-pvc
      persistentVolumeClaim:
        claimName: pvc 
