kind: Pod
apiVersion: v1
metadata:
  name: webapp-color
  labels:
    app: webapp-color
spec: 
  containers:
    - name: webapp-color
      image: mmumshad/simple-webapp-color
      ports:
        - name: webapp-color
          containerPort: 8080
      env:
        - name: APP_COLOR
          value: red

